254 Alertas
fga-eps-mds/2020-2-SiGeD-Demands pull request #35
Opened 2021-05-14 19:05 UTC by DaviMarinho

**Issue:** resolves fga-eps-mds/2020-2-SiGeD#253
 resolves fga-eps-mds/2020-2-SiGeD#254

## Descrição
Deleta alertas e concerta o checkbox dos alertas no backend.

2021-05-14 23:16 UTC, gabibguedes requested changes
Tem duplicações no código

2021-05-14 23:16 UTC, gabibguedes commented on src/Controllers/AlertController.js
> +const alertUpdate = async (req, res) => {
As funções `alertUpdate` e `alertUpdateCheckbox` são iguais.

2021-05-21 01:36 UTC, gabibguedes approved these changes
ok

2021-05-21 03:37 UTC, EzequielDeOliveira approved these changes
LGTM!

2021-05-21 03:37 UTC, merged